language: java

deploy:
  provider: releases
  api_key: "$API_KEY_TWIG"
  file: "target/cassandra-twig-jdbc-2.1.0-jar-with-dependencies.jar"
  skip_cleanup: true
  all_branches: true
  on:
    all-branches: true
    tags: true