language: java

deploy:
  provider: releases
  api_key: "$API_KEY"
  file: "build/libs/cassandra-twig-jdbc-$TRAVIS_TAG.jar"
  skip_cleanup: true
  all_branches: true
  on:
    all-branches: true
    tags: true