language: java

deploy:
  provider: releases
  api_key: {{ REPO_SETTINGS['environment_variables']['API_KEY'] }}
  file: "target/cassandra-twig-jdbc-2.1.0-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true