language: java

deploy:
  provider: releases
  api_key: "$API_KEY"
  file: "target/cassandra-twig-jdbc-$TRAVIS_TAG-jar-with-dependencies.jar"
  skip_cleanup: true
  all_branches: true
  on:
    all-branches: true
    tags: true